export const VISION_FEATURE_FLAGS = {
  ENABLE_PERSPECTIVE_CORRECTION: true,
  ENABLE_HAND_LANDMARKS: true,
  ENABLE_FINGER_SEGMENTATION: false,
  ENABLE_MULTI_SAMPLE_WIDTH: true,
  ENABLE_TEMPORAL_FUSION: true,
  ENABLE_ANATOMICAL_REGION_FUSION: true,
  ENABLE_DEVICE_ORIENTATION: true,
  ENABLE_CAMERA_CORRECTION: false,
  ENABLE_DEPTH_VALIDATION: false,
  ENABLE_DEPTH_FROM_MOTION: false,
} as const;

export type VisionFeatureFlag = keyof typeof VISION_FEATURE_FLAGS;
